apiVersion: v2
appVersion: v1.5.4
description: The Helm chart for Envoy Gateway
home: https://github.com/giantswarm/envoy-gateway-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg
annotations:
  application.giantswarm.io/team: cabbage
name: envoy-gateway
sources:
  - https://github.com/envoyproxy/gateway
type: application
version: 1.1.0
dependencies:
  - name: kubectl-apply-job
    version: "0.11.0-27709f40c9f30209b7b88b650ec2df151e6f8a05"
    repository: oci://giantswarmpublic.azurecr.io/giantswarm-playground-test-catalog
    condition: kubectlApplyJob.enabled
