apiVersion: v2
appVersion: "1.6.3"
description: The Helm chart for Envoy Gateway
home: https://github.com/giantswarm/envoy-gateway-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg
annotations:
  io.giantswarm.application.team: cabbage
name: envoy-gateway
sources:
  - https://github.com/envoyproxy/gateway
type: application
version: 1.4.1
